image: python:latest

cache:
    paths:
        - ~/.cache/pip/

before_script:
    - python -V
    - apt-get update
    - apt-get install ssh-client

stages:
    - deploy

upload_to_server:
    stage: deploy
    before_script:
        - apt-get install -qq git
        - 'which ssh-agent || ( apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - ssh $SSH_USER@$SSH_HOST "cd prodserver_conf/s106_ms && git checkout master && git pull origin master && exit"
        - ssh $SSH_USER@$SSH_HOST "cd prodserver_conf && docker stop s106_ms && docker rm s106_ms && docker-compose build s106_ms && docker-compose up -d s106_ms && exit"
    only:
        - master
