# Generated by Django 3.0 on 2020-03-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='settings',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.TrackSettings'),
            preserve_default=False,
        ),
    ]
