# Generated by Django 3.0 on 2020-04-17 21:30

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='main.MusicTrackProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicInstrumentEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='main.MusicInstrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicInstrumentSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='main.MusicInstrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicInstrumentEffectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='main.MusicInstrumentEffect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
