# Generated by Django 3.0 on 2020-04-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackcomment',
            name='checked_by_author',
        ),
    ]
