# Generated by Django 3.0 on 2020-05-02 20:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_trackcomment_checked_by_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicinstrumentsetting',
            name='instrument',
        ),
        migrations.AddField(
            model_name='musicinstrument',
            name='json_settings',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='musicinstrumenteffect',
            name='json_settings',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='musicinstrument',
            name='type',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='MusicInstrumentEffectSetting',
        ),
        migrations.DeleteModel(
            name='MusicInstrumentSetting',
        ),
    ]
