# Generated by Django 3.0 on 2020-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200323_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrackpattern',
            name='instrument',
        ),
        migrations.AddField(
            model_name='musictrackproject',
            name='instruments',
            field=models.ManyToManyField(related_name='project', to='main.MusicInstrument'),
        ),
    ]
