# Generated by Django 3.0 on 2020-05-07 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200502_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSoundTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundtracks', to='main.MusicInstrument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundtracks', to='main.MusicTrackProject')),
            ],
        ),
        migrations.AlterField(
            model_name='musicnote',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='musicnote',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='musictrackpattern',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='TrackProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('bpm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(999)])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.MusicTrackProject')),
            ],
        ),
        migrations.CreateModel(
            name='TrackPatternInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='main.MusicTrackPattern')),
                ('soundtrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_instances', to='main.InstrumentSoundTrack')),
            ],
        ),
    ]
