# Generated by Django 3.0 on 2020-05-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200507_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackprojectsettings',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='main.MusicTrackProject'),
        ),
    ]
