# Generated by Django 3.0 on 2020-03-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200321_0906'),
        ('main', '0003_auto_20200323_1641'),
    ]

    operations = [
    ]
