# Generated by Django 3.0 on 2020-05-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200507_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackpatterninstance',
            name='soundtrack',
        ),
        migrations.RemoveField(
            model_name='trackprojectsettings',
            name='duration',
        ),
        migrations.AddField(
            model_name='musicnote',
            name='instrument',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.MusicInstrument'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InstrumentSoundTrack',
        ),
    ]
