# Generated by Django 3.0.6 on 2020-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200507_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscibers',
            field=models.ManyToManyField(to='main.Profile'),
        ),
    ]
