# Generated by Django 3.0 on 2020-05-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200510_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to='main.Profile'),
        ),
    ]
