# Generated by Django 3.0 on 2020-05-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200510_1717'),
        ('main', '0006_auto_20200509_0958'),
    ]

    operations = [
    ]
