# Generated by Django 3.0 on 2020-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20200510_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrackpattern',
            name='color',
        ),
        migrations.AddField(
            model_name='musicinstrument',
            name='notesColor',
            field=models.CharField(choices=[('#ff0000', 'red'), ('#00ff00', 'green'), ('#0000ff', 'blue'), ('#00ffff', 'aqua'), ('#ff69b4', 'pink'), ('#cc33ff', 'purple'), ('#ff6600', 'orange')], default='#ff0000', max_length=10),
        ),
    ]
