# Generated by Django 3.0 on 2020-05-15 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200513_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrackpattern',
            name='duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AlterField(
            model_name='trackprojectsettings',
            name='bpm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
