# Generated by Django 3.0 on 2020-05-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200515_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicnote',
            old_name='duration',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='musicnote',
            old_name='position',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='trackpatterninstance',
            old_name='position',
            new_name='time',
        ),
    ]
