# Generated by Django 3.0 on 2020-06-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200530_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrackpattern',
            name='color',
            field=models.CharField(choices=[('#ff0000', 'red'), ('#00ff00', 'green'), ('#0000ff', 'blue'), ('#00ffff', 'aqua'), ('#ff69b4', 'pink'), ('#cc33ff', 'purple'), ('#ff6600', 'orange')], default='#0000ff', max_length=10),
        ),
    ]
