# Generated by Django 3.0 on 2020-06-02 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_musictrackpattern_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackpatterninstance',
            name='track',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
    ]
