# Generated by Django 3.0 on 2020-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200523_1744'),
        ('main', '0015_trackpatterninstance_track'),
    ]

    operations = [
    ]
