# Generated by Django 3.0 on 2020-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_20200603_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='claims',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='music_tracks/'),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='reports',
            field=models.ManyToManyField(related_name='reports', to='main.TrackComment'),
        ),
        migrations.AddField(
            model_name='tracksettings',
            name='access',
            field=models.PositiveIntegerField(choices=[(0, 'private'), (1, 'link'), (2, 'public')], default=2),
            preserve_default=False,
        ),
    ]
