# Generated by Django 3.0 on 2020-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200603_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='reports',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='claims',
            field=models.ManyToManyField(related_name='claims', to='main.TrackComment'),
        ),
    ]
