# Generated by Django 3.0 on 2020-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200603_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
