# Generated by Django 3.0 on 2020-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_oauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='oauth',
            field=models.CharField(max_length=300),
        ),
    ]
