# Generated by Django 3.0 on 2020-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200604_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth',
            field=models.CharField(default='', max_length=300),
        ),
    ]
