# Generated by Django 3.0 on 2020-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200604_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='oauth',
            field=models.CharField(default='', max_length=300),
        ),
    ]
